name = "ResourceAdq"
uuid = "c94ec09b-1913-49f2-b3a0-ce23208a88b1"
authors = ["Tamás Borbáth <borbathtamas@gmail.com> and contributors"]
version = "0.1.0"

[deps]
PRAS = "05348d26-1c52-11e9-35e3-9d51842d34b9"

[compat]
julia = "1.7"
